### ISSUE TITLE
Inverter IN Watts not Showing Solar Panel Input Wattage

### ISSUE THREAD

**Issue by povgride742** [tess1o/go-ecoflow-exporter#17]
Running via rest API... everything showing correctly in Grafana except Inveter IN Watts.
- Tried changing auto refresh interval
- Did not try observing with AC input

![Grafana](https://github.com/user-attachments/assets/b002ff3f-ecf8-4c5b-8571-54ec0fb84f18)
![EcoFlow App](https://github.com/user-attachments/assets/5dcdbd1b-a388-4d54-ad8a-c695193dd74e)

**Comment by povgride742** [comment]
Changed all the targets for inverter INs to the following to achieve what I was looking for:
ecoflow_mppt_in_watts{device="$device"}
ecoflow_mppt_in_vol{device="$device"}
ecoflow_mppt_in_amp{device="$device"}

**Comment by tess1o** [comment]
Hello,

I do not own that Grafana dashboard but this exporter is compatible with it.  In your case you have the Input coming from the solar panels, not the grid.  In Grafana "Inverter IN watts" expects the value from the grid, that's why you had 0. 

To fix this you can adjust the value of `Inverter IN watts` from `ecoflow_pd_watts_in_sum{device="$device"}` to `ecoflow_pd_watts_in_sum{device="$device"} + ecoflow_mppt_in_watts{device="$device"}`. It will sum the input from the grid and from solar panels.

**Comment by povgride742** [comment]
Thank you!
